import { deal_img2, deal_img3, deal_img4 } from "../assets";

export interface Product {
  id: string;
  name: string;      // required
  year: number;      // required
  region: string;    // required
  size: string;      // required
  rating: number;    // required
  price: number;     // required
  vipPrice?: number;
  salePrice?: number;
  tag?: string;
  isWishlisted?: boolean;
  description?: string;
  media: {
    type: "image" | "video";
    url: string;
  };
}


export const DEAL_PRODUCT: Product[] = [
  {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
    {
    id: "1",
    name: "Meiomi Pinot Noir",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Best Seller",
    isWishlisted: true,
    description: "This 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage representsThis 2018 vintage represents",
    media: {
      type: "image",
      url: deal_img4,
    },
  },
  {
    id: "2",
    name: "Josh Cellars Cabernet",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "New Arrival",
    isWishlisted: false,
    description: "Smooth and rich flavor...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
  {
    id: "3",
    name: "Jim Bean Bourbon Whiskey",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Limited Edition",
    isWishlisted: false,
    description: "Classic bourbon taste...",
    media: {
      type: "image",
      url: deal_img3,
    },
  },
  {
    id: "4",
    name: "La Marca Prosecco Sparkling",
    year: 2021,
    region: "California",
    size: "750ML",
    rating: 4.8,
    price: 16.53,
    vipPrice: 12.62,
    salePrice: 11.45,
    tag: "Popular",
    isWishlisted: true,
    description: "Fresh and crisp sparkling wine...",
    media: {
      type: "image",
      url: deal_img2,
    },
  },
];
